language: android
dist: trusty
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.0-rc02
    - build-tools-28.0.3
    - build-tools-27.0.3
    - android-27
    - android-28
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script:
  - ./gradlew ktlint test install --info
  - cd examples/kotlin-example
  - ./gradlew test --tests com.karumi.example.DebugConfigFromExtensionTest --info
  - ./gradlew test --tests com.karumi.example.CIProfileTest -Pprofile=ci --info
  - cd ../multiplatform-example
  - ./gradlew test --info
