language: android
sudo: required
env:
  global:
    - ADB_INSTALL_TIMEOUT=8 # 8 minutes (2 minutes by default)

jdk:
  - oraclejdk9

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.0-rc02
    - build-tools-27.0.3
    - android-27
    - android-28
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository

script:
  - ./gradlew ktlint test install --info
  - ./gradlew install
  - cd examples/kotlin-example
  - ./gradlew test --info
  - cd ../multiplatform-example
  - ./gradlew test --info
