language: java

jdk:
  - oraclejdk11

script:
  - ./gradlew ktlint test install --info
  - ./gradlew install
  - cd examples/kotlin-example
  - ./gradlew test --info
  - cd ../multiplatform-example
  - ./gradlew test --info
